import { BarrelProfile, AmmoLot, TuneSession, EnvironmentalConditions } from '@/types';

// Standard calibration physical dimensions in inches
export const CALIBRATION_STANDARDS = {
  quarter: { name: 'US Quarter (0.955")', diameterInches: 0.955 },
  dime: { name: 'US Dime (0.705")', diameterInches: 0.705 },
  one_inch_square: { name: '1.000" Calibration Square/Ruler', diameterInches: 1.000 },
  ara_ring_100: { name: 'ARA 100-Ring Bull (0.500")', diameterInches: 0.500 },
  custom: { name: 'Custom Dimension', diameterInches: 1.000 },
};

export const DEFAULT_BARRELS: BarrelProfile[] = [
  {
    id: 'lentz-stiller-2500x-shilen-5r',
    serialNumber: 'LP-2024-088',
    name: 'Lentz 2500X Shilen 5R Ratchet',
    gunsmith: 'Jeremiah Lentz (Lentz Precision Rifles)',
    action: 'Stiller 2500X Rimfire Action',
    contour: 'Straight Cylinder 0.900"',
    lengthInches: 24.5,
    muzzleDiameterInches: 0.900,
    twistRate: '1:16.5 5R Ratchet',
    chamberReamer: 'Lentz Match Calfee 2°',
    tunerModel: 'Harrell Standard (50 clicks/rev)',
    tunerWeightOz: 7.2,
    totalRounds: 650,
    notes: 'Primary competition benchrest rifle. Built for Bristol & PSL matches. Likes Lapua Center-X 1060fps lots.',
    createdAt: '2026-04-12T10:00:00Z',
  },
  {
    id: 'lentz-turbo-v1-muller-8g',
    serialNumber: 'LP-2025-104',
    name: 'Lentz Turbo V-1 Muller 8-Groove',
    gunsmith: 'Jeremiah Lentz (Lentz Precision Rifles)',
    action: 'Flash Turbo V-1',
    contour: 'Lentz Heavy Benchrest 0.920"',
    lengthInches: 25.0,
    muzzleDiameterInches: 0.920,
    twistRate: '1:16 8-Groove MI',
    chamberReamer: 'Eley EPS Match 1.5°',
    tunerModel: 'Ezell Precision PDMT',
    tunerWeightOz: 8.0,
    totalRounds: 320,
    notes: 'Tuned for Eley Tenex Black Box. Extremely fast settling time.',
    createdAt: '2026-06-20T14:30:00Z',
  },
  {
    id: 'lentz-rimx-bartlein-gain',
    serialNumber: 'LP-2025-142',
    name: 'Lentz RimX Bartlein Gain-Twist',
    gunsmith: 'Jeremiah Lentz (Lentz Precision Rifles)',
    action: 'Zermatt RimX',
    contour: 'MTU 0.930" Muzzle',
    lengthInches: 22.0,
    muzzleDiameterInches: 0.930,
    twistRate: '1:16.5 to 1:15 Gain',
    chamberReamer: 'Lentz Hybrid Match',
    tunerModel: 'Harrell Standard (50 clicks/rev)',
    tunerWeightOz: 6.8,
    totalRounds: 410,
    notes: 'Cross-discipline rifle for precision rimfire and benchrest testing.',
    createdAt: '2026-08-01T09:00:00Z',
  },
];

export const DEFAULT_AMMO_LOTS: AmmoLot[] = [
  {
    id: 'lapua-cx-lot-31554',
    brand: 'Lapua',
    model: 'Center-X',
    lotNumber: '31554/22532',
    boxMuzzleVelocityFps: 1073,
    measuredAvgFps: 1068,
    standardDeviation: 6.4,
    extremeSpread: 17.0,
    testedTempF: 72,
    ratingStars: 5,
    notes: 'Exceptional lot. Shoots clean 2450+ on ARA cards with Lentz Shilen 5R at 13 clicks.',
  },
  {
    id: 'lapua-midas-lot-4821',
    brand: 'Lapua',
    model: 'Midas+',
    lotNumber: '4821/20489',
    boxMuzzleVelocityFps: 1070,
    measuredAvgFps: 1071,
    standardDeviation: 5.1,
    extremeSpread: 13.0,
    testedTempF: 68,
    ratingStars: 5,
    notes: 'Match reserve lot. Virtually zero vertical when barrel is in sweet spot.',
  },
  {
    id: 'eley-tenex-lot-1023',
    brand: 'Eley',
    model: 'Tenex (Black Box)',
    lotNumber: '1023-04088',
    boxMuzzleVelocityFps: 1060,
    measuredAvgFps: 1058,
    standardDeviation: 7.2,
    extremeSpread: 21.0,
    testedTempF: 75,
    ratingStars: 4,
    notes: 'EPS bullet profile. Very consistent in 8-Groove barrels.',
  },
  {
    id: 'sk-rifle-match-lot-992',
    brand: 'SK',
    model: 'Rifle Match',
    lotNumber: '02899/1012',
    boxMuzzleVelocityFps: 1073,
    measuredAvgFps: 1065,
    standardDeviation: 9.8,
    extremeSpread: 28.0,
    testedTempF: 70,
    ratingStars: 3,
    notes: 'Foul-in & rough tuning ammo before moving to premium lot numbers.',
  },
];

export const DEFAULT_ENVIRONMENT: EnvironmentalConditions = {
  tempF: 74,
  humidityPercent: 55,
  pressureInHg: 29.92,
  elevationFt: 1520, // Bristol / Blountville TN elevation approx 1500-1600 ft
  densityAltitudeFt: 2150,
  windSpeedMph: 4,
  windDirectionClock: 2,
  locationName: 'Blountville Benchrest Range, TN',
  lastUpdated: '2026-09-15T14:30:00Z',
};

export const DEFAULT_TUNING_SESSION: TuneSession = {
  id: 'session-bristol-cup-prep',
  title: 'Lentz Shilen 5R Harrell Sweet Spot Test',
  date: '2026-09-15T14:30:00Z',
  barrelId: 'lentz-stiller-2500x-shilen-5r',
  ammoLotId: 'lapua-cx-lot-31554',
  distanceYards: 50,
  environment: DEFAULT_ENVIRONMENT,
  runs: [
    {
      id: 'run-0',
      tunerClick: 0,
      shotCount: 5,
      verticalSpreadInches: 0.385,
      horizontalSpreadInches: 0.220,
      groupSizeInches: 0.412,
      groupMoa50Yd: 0.787,
      meanRadiusInches: 0.160,
      notes: 'Tuner fully closed (baseline). Noticeable vertical stringing.',
    },
    {
      id: 'run-5',
      tunerClick: 5,
      shotCount: 5,
      verticalSpreadInches: 0.274,
      horizontalSpreadInches: 0.205,
      groupSizeInches: 0.315,
      groupMoa50Yd: 0.602,
      meanRadiusInches: 0.125,
      notes: 'Vertical compressing as node approaches.',
    },
    {
      id: 'run-10',
      tunerClick: 10,
      shotCount: 5,
      verticalSpreadInches: 0.145,
      horizontalSpreadInches: 0.168,
      groupSizeInches: 0.198,
      groupMoa50Yd: 0.378,
      meanRadiusInches: 0.082,
      notes: 'Entering sweet spot window.',
    },
    {
      id: 'run-12',
      tunerClick: 12,
      shotCount: 5,
      verticalSpreadInches: 0.098,
      horizontalSpreadInches: 0.140,
      groupSizeInches: 0.155,
      groupMoa50Yd: 0.296,
      meanRadiusInches: 0.058,
      notes: 'Super tight! Holes cutting together.',
    },
    {
      id: 'run-14',
      tunerClick: 14,
      shotCount: 5,
      verticalSpreadInches: 0.104,
      horizontalSpreadInches: 0.152,
      groupSizeInches: 0.162,
      groupMoa50Yd: 0.309,
      meanRadiusInches: 0.062,
      notes: 'Flat forgiving center of the node.',
    },
    {
      id: 'run-16',
      tunerClick: 16,
      shotCount: 5,
      verticalSpreadInches: 0.118,
      horizontalSpreadInches: 0.170,
      groupSizeInches: 0.188,
      groupMoa50Yd: 0.359,
      meanRadiusInches: 0.071,
      notes: 'Still within forgiving window.',
    },
    {
      id: 'run-20',
      tunerClick: 20,
      shotCount: 5,
      verticalSpreadInches: 0.245,
      horizontalSpreadInches: 0.195,
      groupSizeInches: 0.285,
      groupMoa50Yd: 0.544,
      meanRadiusInches: 0.112,
      notes: 'Leaving node, vertical opening back up.',
    },
    {
      id: 'run-25',
      tunerClick: 25,
      shotCount: 5,
      verticalSpreadInches: 0.340,
      horizontalSpreadInches: 0.230,
      groupSizeInches: 0.375,
      groupMoa50Yd: 0.716,
      meanRadiusInches: 0.148,
      notes: 'Off node completely.',
    },
  ],
  sweetSpotClick: 13,
  sweetSpotWindow: {
    startClick: 11,
    endClick: 15,
    maxVerticalInches: 0.125,
  },
  notes: 'Optimal Harrell setting is 13 clicks. Forgiving window spans 11 to 15 clicks with Lapua lot 31554.',
};
